apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: elastifast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: ghcr.io/nachiket-lab/elastifast:latest
          command:
            #            ["sleep", "300000"]
            ["celery", "-A", "elastifast.tasks", "beat", "--loglevel=info"]
          volumeMounts:
            - name: settings-volume
              mountPath: /app/settings.yaml
              subPath: settings.yaml # Mount only the settings.yaml file
      volumes:
        - name: settings-volume
          secret:
            secretName: elastifast-settings
